#cloud-config
# See the autoinstall documentation at:
# https://canonical-subiquity.readthedocs-hosted.com/en/latest/reference/autoinstall-reference.html
autoinstall:
  apt:
    disable_components: []
    fallback: offline-install
    geoip: true
    mirror-selection:
      primary:
      - country-mirror
      - arches: &id001
        - amd64
        - i386
        uri: http://archive.ubuntu.com/ubuntu/
      - arches: &id002
        - s390x
        - arm64
        - armhf
        - powerpc
        - ppc64el
        - riscv64
        uri: http://ports.ubuntu.com/ubuntu-ports
    preserve_sources_list: false
    security:
    - arches: *id001
      uri: http://security.ubuntu.com/ubuntu/
    - arches: *id002
      uri: http://ports.ubuntu.com/ubuntu-ports
  codecs:
    install: true
  drivers:
    install: true
  identity:
    hostname: antoine
    password: $6$2dDa0UKN78eUp24j$XIXNunv/Mv46dJrqXJiQ7jbN/wTiz.sZ4GbkfNPZ2tNNnz1r/ZrZ/ec2N/fTiopte7aZB4ilwH1wtok9SEPmd/
    realname: antoine
    username: antoine
  kernel:
    package: linux-generic-hwe-24.04
  keyboard:
    layout: us
    toggle: null
    variant: ''
  locale: en_US.UTF-8
  network:
    version: 2
    wifis: {}
  oem:
    install: auto
  packages:
    - bat
    - build-essential
    - curl
    - git
    - gh
    - libbz2-dev
    - libffi-dev
    - liblzma-dev
    - libncursesw5-dev
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - libxml2-dev
    - libxmlsec1-dev
    - lldb
    - llvm
    - make
    - openssl
    - skim
    - tk-dev
    - valgrind
    - vim
    - wget
    - xz-utils
    - yq
    - zlib1g-dev
  source:
    id: ubuntu-desktop-minimal
    search_drivers: true
  ssh:
    allow-pw: false
    authorized-keys: []
    install-server: false
  storage:
    config:
    - transport: pcie
      preserve: true
      id: nvme-controller-nvme0
      type: nvme_controller
    - ptable: gpt
      serial: Micron_2400_MTFDKBA512QFM_23063F840D4A_1
      wwn: eui.000000000000000100a075233f840d4a
      nvme_controller: nvme-controller-nvme0
      path: /dev/nvme0n1
      wipe: superblock-recursive
      preserve: false
      name: ''
      grub_device: false
      id: disk-nvme0n1
      type: disk
    - device: disk-nvme0n1
      size: 1127219200
      wipe: superblock
      flag: boot
      number: 1
      preserve: false
      grub_device: true
      offset: 1048576
      path: /dev/nvme0n1p1
      id: partition-0
      type: partition
    - fstype: fat32
      volume: partition-0
      preserve: false
      id: format-1
      type: format
    - device: disk-nvme0n1
      size: 510980521984
      wipe: superblock
      number: 2
      preserve: false
      offset: 1128267776
      path: /dev/nvme0n1p2
      id: partition-1
      type: partition
    - fstype: ext4
      volume: partition-1
      preserve: false
      id: format-2
      type: format
    - path: /
      device: format-2
      id: mount-1
      type: mount
    - path: /boot/efi
      device: format-1
      id: mount-0
      type: mount
  timezone: Europe/Paris
  updates: security
  version: 1
