---
- name: Import the Google Cloud public key
  become: yes
  become_method: sudo
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
    keyring: /usr/share/keyrings/cloud.google.gpg

- name: Cloud SDK distribution URI as a package source
  become: yes
  become_method: sudo
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main
    state: present
    filename: google-cloud-sdk
