---
- name: Add Google Cloud SDK repository
  become: yes
  become_method: sudo
  yum_repository:
    name: google-cloud-sdk
    description: Google Cloud SDK YUM repo
    file: google-cloud-sdk
    baseurl: https://packages.cloud.google.com/yum/repos/cloud-sdk-el8-x86_64
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: 0
    gpgkey:
      - https://packages.cloud.google.com/yum/doc/yum-key.gpg
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_repository_module.html
    # https://cloud.google.com/sdk/docs/install#rpm
