---
- name: Get Google Cloud SDK
  become: yes
  become_method: sudo
  package:
    name: google-cloud-sdk
    state: present
    update_cache: yes

- name: Get additional Google Cloud SDK components
  become: yes
  become_method: sudo
  package:
    name: '{{ item }}'
    state: present
  with_items: "{{ gcloud.additional_components }}"

- name: Initialize or Reinitialize gcloud
  command:
    argv:
      - gcloud
      - init
