---
- name: Import the GitHub public key
  become: yes
  become_method: sudo
  apt_key:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    state: present
    keyring: /usr/share/keyrings/githubcli-archive-keyring.gpg

- name: GitHub CLI URI as a deb package source
  become: yes
  become_method: sudo
  apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main
    state: present
    filename: github-cli
