---
- name: Get theme
  get_url:
    url: 'https://github.com/EliverLara/Sweet/releases/download/2.0/Sweet-Dark.tar.xz'
    dest: '/tmp/Sweet-Dark.tar.xz'
    mode: '0664'

- name: Unarchive theme
  become: yes
  become_method: sudo
  unarchive:
    src: '/tmp/Sweet-Dark.tar.xz'
    dest: '/usr/share/themes/'

- name: Set gtk-theme
  community.general.dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Sweet-Dark'"
    state: present

- name: Set theme
  community.general.dconf:
    key: "/org/gnome/desktop/wm/preferences/theme"
    value: "'Sweet-Dark'"
    state: present

- name: Check cursors
  stat:
    path: /usr/share/icons/candy-icons/
  register: curs

- name: Get cursors
  become: yes
  become_method: sudo
  when: curs.stat.exists == false | default(false)
  git:
    repo: 'https://github.com/EliverLara/candy-icons'
    dest: /usr/share/icons/candy-icons
    clone: yes

- name: Delete .git directory
  become: yes
  become_method: sudo
  file:
    state: absent
    path: '/usr/share/icons/candy-icons/.git/'

- name: Set icon-theme
  community.general.dconf:
    key: "/org/gnome/desktop/interface/icon-theme"
    value: "'candy-icons'"
    state: present

- name: Set clock
  community.general.dconf:
    key: "/org/gnome/desktop/interface/clock-show-weekday"
    value: "true"
    state: present

- name: Get terminal default profile
  shell: 'gsettings get org.gnome.Terminal.ProfilesList default | xargs echo'
  register: termprofile

- name: Display terminal profile id
  debug:
    msg: '{{ termprofile.stdout }}'

- name: Set terminal theme variant
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/theme-variant"
    value: "'dark'"
    state: present

- name: Set terminal background-color
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:{{ termprofile.stdout }}/background-color"
    value: "'rgb(0,0,0)'"
    state: present

- name: Set terminal foreground-color
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:{{ termprofile.stdout }}/foreground-color"
    value: "'rgb(208,207,204)'"
    state: present

- name: Set terminal use-system-font
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:{{ termprofile.stdout }}/use-system-font"
    value: 'false'
    state: present

- name: Set terminal use-theme-colors
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:{{ termprofile.stdout }}/use-theme-colors"
    value: 'false'
    state: present

- name: Set wallpaper
  when: gnome.wallpaper | default(false)
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///usr/share/backgrounds/gnome/adwaita-timed.xml'"
    state: present
