---
#  find:
#    paths: "{{ item }}"
#    patterns: kustomize
#  with_items:
#    - /bin/
#    - /usr/local/sbin/
#    - /usr/local/bin/
#    - /usr/sbin/
#    - /usr/bin/
#    - /sbin/
#    - /bin/
#    - /snap/bin/
#  register: ifkustomize
#  debug:
#    msg:
#      - "{{ ifkustomize.results }}"
#  when: ifkustomize.results is defined

- name: Find if a version of Kustomize is installed
  stat:
    path: /usr/local/bin/kustomize
  register: ifkustomize

- name: Get Kustomize script
  get_url:
    url: https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh
    dest: /tmp/
    mode: 0755
  when: ifkustomize.stat.exists == false

- name: Delete previous bin in /tmp
  file:
    path: /tmp/kustomize
    state: absent

- name: Execute setup Kustomize script
  become: yes
  become_method: sudo
  shell:
    cmd: ./install_kustomize.sh /usr/bin
    executable: /bin/bash
    chdir: /tmp/
  when: ifkustomize.stat.exists == false

- name: Set completion
  lineinfile:
    path: "~/.{{ lookup('env', 'SHELL') | basename | default('bash', True) }}rc"
    line: "source <(/usr/bin/kustomize completion {{ lookup('env', 'SHELL') | basename | default('bash', True) }})"
  when: kustomize.autocompletion | default(false)
