- name: Get Stack script
  get_url:
    url: https://get.haskellstack.org/
    dest: /tmp/get-stack.sh
    mode: 0755

- name: Execute setup Stack script
  become: yes
  become_method: sudo
  shell:
    cmd: './get-stack.sh -f'
    executable: /bin/sh
    chdir: /tmp/

- name: Set Stack completion
  lineinfile:
    path: "~/.{{ lookup('env', 'SHELL') | basename | default('bash', True) }}rc"
    line: 'eval "$(stack --bash-completion-script stack)"'
  when: (lookup('env', 'SHELL') == '/bin/bash' and haskell.autocompletion) | default(false)
