---
- name: Remove bluetooth nd related packages
  become: yes
  become_method: sudo
  apt:
    name:
      - blueman
      - bluez-utils
      - bluez
      - bluetooth
    purge: yes
    state: absent

- name: Remove dependencies that are no longer required
  become: yes
  become_method: sudo
  apt:
    autoremove: yes

- name: Remove useless packages from the cache
  become: yes
  become_method: sudo
  apt:
    autoclean: yes
