---
#  find:
#    paths: "{{ item }}"
#    patterns: kustomize
#  with_items:
#    - /bin/
#    - /usr/local/sbin/
#    - /usr/local/bin/
#    - /usr/sbin/
#    - /usr/bin/
#    - /sbin/
#    - /bin/
#    - /snap/bin/
#  register: ifkustomize
#  debug:
#    msg:
#      - "{{ ifkustomize.results }}"
#  when: ifkustomize.results is defined

- name: Find if a version of Flux is installed
  stat:
    path: /usr/local/bin/flux
  register: iflux

- name: Get Flux script
  get_url:
    url: https://fluxcd.io/install.sh
    dest: /tmp/
    mode: 0755
  when: iflux.stat.exists == false

- name: Execute setup Flux script
  shell:
    cmd: ./install.sh
    executable: /bin/bash
    chdir: /tmp
  when: iflux.stat.exists == false

- name: Set completion
  lineinfile:
    path: "~/.{{ lookup('env', 'SHELL') | basename | default('bash', True) }}rc"
    line: "source <(flux completion {{ lookup('env', 'SHELL') | basename | default('bash', True) }})"
  when: flux.autocompletion | default(false)
