---
- name: Install git
  become: yes
  become_method: sudo
  package:
    name: git
    state: latest

- name: Set git name
  git_config:
    name: user.name
    scope: global
    value: '{{ git.user }}'

- name: Set git email
  git_config:
    name: user.email
    scope: global
    value: '{{ git.email }}'

- name:
  when: git.credentials.store | default(false)
  git_config:
    name: credential.helper
    scope: global
    value: store

