---
#  find:
#    paths: "{{ item }}"
#    patterns: glab
#  with_items:
#    - /bin/
#    - /usr/local/sbin/
#    - /usr/local/bin/
#    - /usr/sbin/
#    - /usr/bin/
#    - /sbin/
#    - /bin/
#    - /snap/bin/
#  register: ifglab
#  debug:
#    msg:
#      - "{{ ifglab.results }}"
#  when: ifglab.results is defined

- name: Find if a version of Gitlab is installed
  stat:
    path: /usr/bin/glab
  register: ifglab

- name: Get Gitlab script
  get_url:
    url: https://raw.githubusercontent.com/profclems/glab/trunk/scripts/install.sh
    dest: /tmp/gitlab_install.sh
    mode: 0755
  when: ifglab.stat.exists == false

- name: Execute setup Gitlab script
  become: yes
  become_method: sudo
  shell:
    cmd: ./gitlab_install.sh
    executable: /bin/bash
    chdir: /tmp/
  when: ifglab.stat.exists == false

- name: Set completion
  lineinfile:
    path: "~/.{{ lookup('env', 'SHELL') | basename | default('bash', True) }}rc"
    line: "source <(glab completion -s {{ lookup('env', 'SHELL') | basename | default('bash', True) }})"
  when: gitlab.autocompletion | default(false)
