name: release
run-name: release ${{github.ref_name}}

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

permissions: {}

env:
  GITHUB_TOKEN: ${{github.token}}

defaults:
  run:
    shell: bash

jobs:
  note:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 #4.2.1
    - run: gh release create ${{github.ref_name}} --generate-notes

  release:
    needs: note
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 #4.2.1
    - run: git archive --format=tar.gz --output=conf-${{github.ref_name}}.tar.gz HEAD
    - run: gh release upload ${{github.ref_name}} conf-${{github.ref_name}}.tar.gz
