name: Shellcheck

on: push

permissions: {}

jobs:
  shellcheck:
    strategy:
      matrix:
        include:
          - dir: ./tools
            options: -s sh -e SC1091
          - dir: ./bashrc.d
            options: -s sh -e SC214 -e SC1090 -e SC1090
          - dir: ./init.sh
            options: -s sh
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ludeeus/action-shellcheck@master
        with:
          scandir: ${{ matrix.dir }}
        env:
          SHELLCHECK_OPTS: ${{ matrix.options }}
