name: Tests

on: [push]

permissions: {}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        tool: [ansible, aws, bash, bitwarden, c, git, hadolint, hclq, jq, kubectx, kubens, kustomize, python, rust, shellcheck, ssh, terraformdocs, terraform, tfam, tfexe, tflint, tfswitch, vault, vim, yq]
    steps:
      - run: echo "JOB_NAME=${{ matrix.tool }} on ${{ matrix.os }}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: ${{ matrix.tool }} ${{ matrix.os }}
        run: ./init.sh ${{ matrix.tool }}
