name: Tests

on: [push]

permissions: {}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        os: [ubuntu-latest]
          #os: [ubuntu-latest, macos-latest]
        tool:
          - ansible
          - aws
          - c
          - hadolint
          - hclq
          - jq
          - kubectx
          - kubens
          - kustomize
          - python
          - rust
          - shellcheck
          - terraformdocs
          - terraform
          - tfam
          - tfexe
          - tflint
          - tfswitch
          - vault
          - vim
          - yq
          - opentofu
    steps:
      - uses: actions/checkout@v3
      - name: ${{ matrix.tool }} ${{ matrix.os }}
        run: ./init.sh ${{ matrix.tool }}
