name: tests

on: [push]

permissions: {}

jobs:
  list:
    runs-on: ubuntu-latest
    outputs:
      files: ${{steps.ls.outputs.files}}
    steps:
      - id: ls
        run: echo files="$(ls tools/ | sed 's/.install.sh//' | xargs jq -c -n '$ARGS.positional' --args)" >> "$GITHUB_OUTPUT"

  test:
    needs: list
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        files: ${{fromJSON(needs.list.outputs.files)}}
        steps:
          - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 #4.2.1
          - name: ${{matrix.files}}
            run: ./init.sh ${{matrix.files}}
